# site settings
title: Forty
subtitle: by HTML5 UP
email: davidzsy20@yahoo.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 4310 Crescent
city: NYC
state: NY
zip_code: 11101
country: United States of America
phone: (805) 886-8113

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/Davidzsy20
googleplus_url: 
instagram_url: https://www.instagram.com/nh_zou/
linkedin_url: https://www.linkedin.com/in/david-s-zou-a6798975/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
